### ISSUE TITLE
[Feat] Home, MyInfo 디테일한 수정 작업

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#110]
### 작업에 대한 간단한 설명
- Home, MyInfo 디테일한 수정 작업

### TODO
- [ ] HomeView background color 수정
- [ ] 전체적인 코드 정리
- [ ] 버튼 눌림 효과
