### ISSUE TITLE
[Fix] SplitShareView 버그 수정

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#111]
### 작업에 대한 간단한 설명
- SplitShareView 버그 수정

### TODO
- [ ] VM 안먹은 사람 잘못 추가되는 로직 수정
- [ ] TableView 밑줄 버그 수정
- [ ] 공유하기 버튼 클릭 시 캡처 이미지 화질 개선 및 전체 내용 모두 다 나오도록 수정

### 작업 일정(Optional)
2023.10.25 - 2023.10.25 (작업일자)
