### ISSUE TITLE
[Feat] CSExclItemInput 뷰를 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#134]
### 작업에 대한 간단한 설명
- ExclItem의 name, price, member를 입력, 수정, 삭제, 확인 할 수 있는 해당 뷰를 구현합니다.

### TODO
- [ ] 본 화면의 레이아웃 구현
- [ ] 본 화면의 비즈니스로직 구현
- [ ] 모달 화면의 레이아웃 구현
- [ ] 모달 화면의 비즈니스 로직 구현

### 작업 일정(Optional)
2023.10.29 - 2023.10.30
