### ISSUE TITLE
[Fix] QA리스트 수정

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#152]
### 작업에 대한 간단한 설명
- 디자인 시스템 누락된 부분 적용
- 기타 수정된 부분 적용

### TODO
- [x] MyInfo 디자인 시스템 적용
- [x] 헤더 적용
- [ ] alert창 구현, 연결
- [x] 유저 정보 전체 삭제 구현
- [x] splash 뷰 수정
- [ ] MyInfoVC 수정
    - [x] 1. leading, trailing으로 위치, 크기 맞춰줘야함. 
    - [x] 2. height는 잡아도 되는데, width는 잡아주지 말아야 함. 
    - [x] 3. 정산자 이름 ~ 수정하기> 까지의 영역을 Tap 가능하게 반영 
    - [ ] 4. 입력 가능한 최대 글자수에 도달해도 warn이 되지 않음 
    - [ ] 5. 저장하지 않았는데 은행/간편페이 내역이 저장됨 
    - [ ] 6. 저장된 이름/계좌/예금주명이 data값이 아닌 place holder로 표시됨
- [ ] MyBankAccountVC 수정
    - [x] 1. textField width값 상수 값 말고 leading, trailing 으로 수정 
    - [ ] 2. ‘은행을 선택해주세요’ 값이 MyInfoVC로 안가게 수정하기 
    - [x] 3. 계좌번호 입력되는 textField 글자 수 제한 
    - [x] 4. 뷰의 공백부분 눌렀을때 키보드가 내려가게 
    - [x] 5. 뷰를 탭했을 때, 키보드 내려가게 
    - [ ] 6. 은행의 이름이 변화가 감지가 안되고 있음. 바뀌면 저장되게끔 combineLatest 로 확인 
    - [x] 7. 저장하기 버튼 없애고 확인 버튼 추가
    - [x]  8. 초기화 버튼 추가 필요
