### ISSUE TITLE
[Design] memberSearchView를 수정합니다

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#156]
### 작업에 대한 간단한 설명
- memberSearchView를 수정합니다

### TODO
- [ ] memberSearchView에서 검색된 결과가 없을 시 안내문구를 추가합니다
- [ ] 추가 버튼을 수정합니다
- [ ] TextField 전체 삭제 버튼을 활성화합니다

### 작업 일정(Optional)
2023.11.01 - 2022.11.01 (작업일자)
