### ISSUE TITLE
[Feat] HomeView 생성 및 연관 작업 진행합니다

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#18]
### 작업에 대한 간단한 설명
- HomeView 생성 및 연관 작업 진행합니다

### TODO
- [x] HomeView 생성 및 UI 작업
- [x] HomeViewModel 생성 및 binding
- [ ] HomeViewModel과 Repository 연결

### 작업 일정(Optional)
2023.10.17 - 2022.10.18 (작업일자)
