### ISSUE TITLE
[Feat] SPAlertController를 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#193]
### 작업에 대한 간단한 설명
- 모든 뷰에서 사용가능한 SPAlertController를 구현합니다.

### TODO
- [x] SPAlertController의 레이아웃 구현
- [x] item, title, subtitle, leftButton, rightButton을 추상화합니다.
- [x] leftButton, rightButton의 completion을 rx로 구현합니다.

### 작업 일정(Optional)
2023.11.05 - 2023.11.05
