### ISSUE TITLE
[Feat] ExclItem 관련 Cycle을 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#20]
### 작업에 대한 간단한 설명
- ExclItem 관련 Cycle을 구현합니다.

### TODO
- [ ] ExclItem의 name을 input하는 뷰를 구현합니다.
- [ ] ExclItem의 price를 input하는 뷰를 구현합니다.
- [ ] ExclItem의 target의 배열을 input하는 뷰를 구현합니다.

### 작업 일정(Optional)
2023.10.17 - 2023.10.18
