### ISSUE TITLE
[Feat] HistoryView 구현합니다

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#23]
### 작업에 대한 간단한 설명
- 작업 자체에 대한 간단한 요약 설명

### TODO
- [x] HistoryView 기본 레이아웃 배치
- [x] ViewModel과 View binding
- [x] ViewModel과 Repository 연결

### 작업 일정(Optional)
2023.10.18 - 2022.10.19 (작업일자)
