### ISSUE TITLE
[Fix] MyBankAccountView 수정 

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#238]
### 작업에 대한 간단한 설명
- MyBankAccountView와 관련된 Hi-Fi 관련 수정합니다.

### TODO
- [ ] bankView를 textField로 변환
- [ ] BehaviorRelay로 연결 및 은행 and 계좌 둘 다 받도록 설정
- [ ] 수정안했는데 뒤로가기 누를 시 alert창 뜨는 것 수정
