### ISSUE TITLE
[Feat] 개발단에 Design System을 정의합니다.

### ISSUE THREAD

**Issue by pscu91** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#24]
### 작업에 대한 간단한 설명
- 개발자들의 생산성을 위하여 Design System을 정의합니다.

### TODO
- [x] Color Token 작업
- [x] Typeface Token 작업
  - [x] Font Setup
  - [x] 적용 시 아래의 문제 발생... 해결!
  `Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value`
- [x] Button 컴포넌트 작업
- [x] PopUp Button 컴포넌트 작업
- [x] Image Assets 추가
- [x] HalfButton 컴포넌트 작업
- [x] TextField 컴포넌트 작업
- [x] 더미 App Icon 추가

### 작업 일정
2023.10.18 - 2022.10.20

|작업일자|작업 내용|
|:---:|:---:|
|2023.10.18|이슈 및 브랜치 생성|
|2023.10.18|UIColor, Color Token 작업|
|2023.10.18|UIFont, Typeface Token 작업, Font ttf 파일 설치|
|2023.10.18|SPButton, 일반 Button 컴포넌트 작업|
|2023.10.19|SPButton, 코드 리팩토링|
|2023.10.19|SPTextField, TextField 컴포넌트 작업|
|2023.10.19|Image Assets, 더미 App Icon 적용|
|2023.10.19|SPButton, 팝업용 사각 버튼 디자인 정의|
|2023.10.19|SPButton, Half Button 디자인 정의|
|2023.10.19|UIFont, Typeface Token 적용시 해당 뷰 에러 발생...|
|2023.10.20|UIFont, 위의 문제 해결!|
|2023.10.20|SPButton, SPTextField, Custom Typeface 적용|

### UIColor+ Example
```Swift

...

$0.layer.borderColor = UIColor.BorderPrimary.cgColor
$0.backgroundColor = .SurfaceBrandCalmshell

...

```

### UIFont+ Example
```Swift

...

$0.font = UIFont.KoreanCaption1

...

$0.titleLabel?.font = UIFont.KoreanButtonText

...

```

### SPButton Example | HomeVC
```Swift
  class HomeVC: UIViewController {
      ...

      let splitItButton = SPButton()

      ...
  }
    ...

        splitItButton.do {
            $0.setTitle("♦ Split it!", for: .normal) // 버튼의 타이틀을 설정합니다.
            $0.applyStyle(.primaryWatermelon) // 버튼의 스타일을 설정합니다.
        }       
 
    ...
```

### SPTextField Example | CSTitleInputVC
```Swift
  class CSTitleInputVC: UIViewController {
      ...

      let titleTextFiled = SPTextField()

      ...
  }
    ...

        titleTextFiled.do {
            $0.applyStyle(.normal) // 텍스트 필드의 타이틀을 설정합니다.
        }

    ...
```

### 스크린샷
|기본|눌렸을 때|비활성|
|:---:|:---:|:---:|
|![Simulator Screenshot - iPhone 14 Pro - 2023-10-19 at 18 20 53](https://github.com/DeveloperAcademy-POSTECH/MacC-Team13-SplitIt/assets/91787174/fd90eb20-3f4a-4cae-b6df-c6b38e79f9bd)|![Simulator Screenshot - iPhone 14 Pro - 2023-10-19 at 18 21 02](https://github.com/DeveloperAcademy-POSTECH/MacC-Team13-SplitIt/assets/91787174/16686d6e-3029-45de-b783-5d518d13d88c)|![Simulator Screenshot - iPhone 14 Pro - 2023-10-19 at 18 21 28](https://github.com/DeveloperAcademy-POSTECH/MacC-Team13-SplitIt/assets/91787174/1fdd5dd2-bc72-444e-8474-03d8348dc31e)|
