### ISSUE TITLE
[Fix] QA를 통해 나온 수정사항들을 수정합니다.

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#247]
### 작업에 대한 간단한 설명
-  QA를 통해 나온 수정사항 수정

### TODO
- [x] HistoryView에서 하단의 패딩을 없앱니다.
- [x] SplitMethodView가 SE3에서 이미지가 깨지는 현상을 수정합니다.
- [x] SplitShareVC에서 정산 결과 공유 시, 간편 페이 정보 전달이 되지 않던 부분을 수정합니다.
- [x] SplitMethod, History, SplitShare의 header top constraint를 8로 수정합니다.

### 작업 일정(Optional)
2023.11.09 - 2023.11.09 (작업일자)
