### ISSUE TITLE
[Refactor] 사용하지 않는 코드를 제거합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#262]
### 작업에 대한 간단한 설명
- 제거

- 구 Edit Flow
- ExclEdlitPageController
- CSExclItemMemberEdit
- CSExclItemPriceEdit
- CSExclItemNameEdit
- CSTotalAmountEdit
- CSMemberEdit
- CSTitleEdit
- CSEditMain

- 구 Create Flow
- CSMemberSearch
- CSMember
- CSTotalAmount
- CSTitle
- CreateStore
- ExclItemCycle

- 구 Result
- Result

- 구 Alert
- AlertView

- 구 SPButton
- SPButton 삭제
- NewSPButton -> SPButton으로 Rename

- 구 NaviHeader
- NaviHeader

- Custom Keyboard를 Utility로 move

### TODO
- [ ] 위 레거시 코드들 삭제
- [ ] Custom Keyboard를 Utility로 move
- [ ] EditFlow의 View, ViewModel 폴더링

### 작업 일정(Optional)
2023.11.13 - 2023.11.13
