### ISSUE TITLE
[Feat] Swipe Gesture로 뒤로가기 기능을 추가합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#264]
### 작업에 대한 간단한 설명
- Swipe Gesture로 뒤로가기 기능을 추가
- Alert가 없는 뷰에 gesture로 뒤로 가기 기능 추가
- Alert가 존재 하는 뷰에는 따로 GestureRecognizer를 통해 뒤로가기 기능 추가

### TODO
- [x] Swipe Gesture로 뒤로가기 기능을 추가
- [ ] Alert가 존재하는 뷰에 swipe back 기능 추가
- [ ] Alert가 존재하지 않는 뷰에 swipe back 기능 추가

### 작업 일정(Optional)
2023.11.13 - 2023.11.13
