### ISSUE TITLE
[Fix] keyboard 리팩토링 및 MyBankAccount 저장 분기처리 수정

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#267]
### 작업에 대한 간단한 설명
- Keyboard 리팩토링 및 MyBankAccount 저장 분기처리 수정

### TODO
- [x] Keyboard border 처리
- [ ] Keyboard custom과 account 하나로 합치기
- [ ] MybankAccount 저장버튼 분기처리 수정

### 작업 일정(Optional)
2023.11.13 - 2023.11.13
