### ISSUE TITLE
[Fix] MyBankAccount Hi-Fi UI로 변경

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#275]
### 작업에 대한 간단한 설명
- MyBankAccount 뷰를 Hi-Fi대로 변경합니다

### TODO
- [x] 정산 내역 부분 추가
- [x] memberLog 모두 지우기와 인원 수 추가
- [x] 은행 선택 모달 부분 확인 
- [ ] 은행 List 점검
- [ ] 은행 '선택 안함' 일 때의 MyInfo UI 변경

### 작업 일정(Optional)
2023.11.14 - 2022.11.14
