### ISSUE TITLE
[Fix] 자잘한 수정사항을 수정합니다.

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#282]
### 작업에 대한 간단한 설명
- 작업 자체에 대한 간단한 요약 설명

### TODO
- [x] MemberLog 전체 삭제하는 로직 만들기
- [x] CSMemberVC 네비게이션에 컨트롤러 연결하기
- [x] Flow Enum 만들어서 주입해주기

### 작업 일정(Optional)
2023.11.15 - 2023.11.15
