### ISSUE TITLE
[Fix] MyInfo, MyBank관련 뷰 코드 정리 및 디테일 추가합니다.

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#310]
### 작업에 대한 간단한 설명
- MyInfo, MyBank관련 뷰 코드 정리 및 디테일 추가합니다.

### TODO
- [ ] MemberLogView 모두 지우기 함수 추가
- [ ] BankList 내역 수정
- [ ] SPTextField autocorrectionType 추가
- [ ] 각 뷰들 코드 정리
