### ISSUE TITLE
[Fix] 출시전 자잘한 수정사항을 수정합니다.

### ISSUE THREAD

**Issue by jincode93** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#327]
### 작업에 대한 간단한 설명
- 출시전 자잘한 수정사항을 수정합니다.

### TODO
- [x] SPButton에 darken 추가 및 SplitShare에 적용
- [x] ExclItemVC 숫자키보드에 00 적용
- [x] 디자이너와 함께 확인 후 추가 수정사항 수정

### 작업 일정
2023.11.20 - 2023.11.20
