### ISSUE TITLE
[Feat] textField 내 삭제에 필요한 버튼 및 키보드를 설정합니다

### ISSUE THREAD

**Issue by chaewon-moana** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#54]
### 작업에 대한 간단한 설명
- textField의 글자 한번에 지우는 버튼 생성
- textField에 맞게 키보드 설정
- 

### TODO
- [ ] 디테일한 버튼 수정 작업
- [ ] 상황에 맞는 키보드 작업
- [ ] 친구목록 search에서 한국어 -> 영어 순으로 sort되도록 구현
