### ISSUE TITLE
[Feat] CSMemberInput 뷰를 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#6]
### 작업에 대한 간단한 설명
- CSMemberInputVC를 구현합니다.
- CSMemberInputVM를 구현합니다.

### TODO
- [x] searchTextField에 따른 SearchView 구현 (Member Create)
- [x] 현재 CS의 Member를 표현하는 TableView 구현
- [x] TableView에서 Member의 Delete 기능
- [x] NextButton에서 현재 Member를 Observe
- [x] Member의 name 길이 Counter 구현

### 작업 일정(Optional)
2023.10.16 - 2023.10.16
