### ISSUE TITLE
[Feat] CSMemberConfirm 뷰를 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [DeveloperAcademy-POSTECH/MacC-Team13-SplitIt#9]
### 작업에 대한 간단한 설명
- CSMemberConfirm 뷰를 구현합니다.

### TODO
- [x] CSTitleInput 뷰에서 입력한 title을 TableViewHeader에 바인딩
- [x] CSTotalAmountInput 뷰에서 입력한 totalAmount를 TableViewHeader에 바인딩
- [x] CSMemberInput 뷰에서 입력한 member를 TableViewHeader에 바인딩
- [x] tableView 레이아웃 구현

### 작업 일정(Optional)
2023.10.17 - 2022.10.17
